// This file is auto-generated by scripts/fetch-network-limits.mjs
// DO NOT EDIT MANUALLY

export interface NetworkLimits {
  // Per-transaction limits
  tx_max_instructions: number;
  tx_memory_limit: number;
  tx_max_footprint_entries: number;
  tx_max_disk_read_entries: number;
  tx_max_write_ledger_entries: number;
  tx_max_disk_read_bytes: number;
  tx_max_write_bytes: number;
  tx_max_contract_events_size_bytes: number;
  contract_data_key_size_bytes: number;
  contract_max_size_bytes: number;

  // Ledger-wide limits
  ledger_max_instructions: number;
  ledger_max_disk_read_entries: number;
  ledger_max_disk_read_bytes: number;
  ledger_max_write_ledger_entries: number;
  ledger_max_write_bytes: number;
  ledger_max_txs_size_bytes: number;

  // State archival TTL extension parameters
  max_entry_ttl: number;
  min_temporary_ttl: number;
  min_persistent_ttl: number;

  // Resource fees (in stroops)
  fee_rate_per_instructions_increment: number;
  fee_read_ledger_entry: string;
  fee_write_ledger_entry: string;
  fee_read_1kb: string;
  fee_write_1kb: string;
  fee_tx_size_1kb: string;
  fee_historical_1kb: string;
  fee_contract_events_1kb: string;
  persistent_rent_rate_denominator: string;
  temp_rent_rate_denominator: string;
  live_soroban_state_size_window: string[];

  // Rent-related config parameters for computing fee_per_rent_1kb
  state_target_size_bytes: string;
  rent_fee_1kb_state_size_low: string;
  rent_fee_1kb_state_size_high: string;
  state_size_rent_fee_growth_factor: number;
}

export const MAINNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 17280,
  "min_persistent_ttl": 2073600,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "746930823",
    "747288967",
    "748229351",
    "748383383",
    "748883051",
    "748860867",
    "749467467",
    "750150803",
    "750332419",
    "750931059",
    "750707179",
    "751600303",
    "752141183",
    "752377115",
    "752580571",
    "752756551",
    "753797775",
    "754130955",
    "754268806",
    "755100130",
    "755540982",
    "756408342",
    "756014486",
    "756127442",
    "756527322",
    "756698394",
    "757013814",
    "757268902",
    "757427150",
    "757956570"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const TESTNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "1287137233",
    "1287144401",
    "1287133973",
    "1288008979",
    "1288407510",
    "1283967874",
    "1280085604",
    "1280866331",
    "1281356883",
    "1281084626",
    "1282053871",
    "1282937857",
    "1282967025",
    "1282967513",
    "1283281195",
    "1283490209",
    "1285545621",
    "1285567721",
    "1285600621",
    "1286077103",
    "1286088831",
    "1286092831",
    "1286096483",
    "1286119671",
    "1286245778",
    "1286365538",
    "1286415789",
    "1286306421",
    "1286128537",
    "1286358375"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const FUTURENET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334",
    "70219334"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const NETWORK_LIMITS: Record<string, NetworkLimits> = {
  mainnet: MAINNET_LIMITS,
  testnet: TESTNET_LIMITS,
  futurenet: FUTURENET_LIMITS,
} as const;
