// This file is auto-generated by scripts/fetch-network-limits.mjs
// DO NOT EDIT MANUALLY

export interface NetworkLimits {
  // Per-transaction limits
  tx_max_instructions: number;
  tx_memory_limit: number;
  tx_max_footprint_entries: number;
  tx_max_disk_read_entries: number;
  tx_max_write_ledger_entries: number;
  tx_max_disk_read_bytes: number;
  tx_max_write_bytes: number;
  tx_max_contract_events_size_bytes: number;
  contract_data_key_size_bytes: number;
  contract_max_size_bytes: number;

  // Ledger-wide limits
  ledger_max_instructions: number;
  ledger_max_disk_read_entries: number;
  ledger_max_disk_read_bytes: number;
  ledger_max_write_ledger_entries: number;
  ledger_max_write_bytes: number;
  ledger_max_txs_size_bytes: number;

  // State archival TTL extension parameters
  max_entry_ttl: number;
  min_temporary_ttl: number;
  min_persistent_ttl: number;

  // Resource fees (in stroops)
  fee_rate_per_instructions_increment: number;
  fee_read_ledger_entry: string;
  fee_write_ledger_entry: string;
  fee_read_1kb: string;
  fee_write_1kb: string;
  fee_tx_size_1kb: string;
  fee_historical_1kb: string;
  fee_contract_events_1kb: string;
  persistent_rent_rate_denominator: string;
  temp_rent_rate_denominator: string;
  live_soroban_state_size_window: string[];

  // Rent-related config parameters for computing fee_per_rent_1kb
  state_target_size_bytes: string;
  rent_fee_1kb_state_size_low: string;
  rent_fee_1kb_state_size_high: string;
  state_size_rent_fee_growth_factor: number;
}

export const MAINNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 17280,
  "min_persistent_ttl": 2073600,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "930230351",
    "930266491",
    "930844915",
    "931442887",
    "931350331",
    "931636159",
    "931783579",
    "932478871",
    "933226367",
    "933253155",
    "933582599",
    "933934243",
    "934927763",
    "936134955",
    "936603231",
    "936720579",
    "937244383",
    "938265499",
    "939339463",
    "939620039",
    "939989975",
    "940203715",
    "938755875",
    "939712715",
    "939907007",
    "940579887",
    "940945059",
    "941822275",
    "942656827",
    "942622639"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const TESTNET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "1027144640",
    "1027304210",
    "1027269250",
    "1029191911",
    "1030431019",
    "1031660231",
    "1032924683",
    "1034134719",
    "1035381874",
    "1036554726",
    "1036996930",
    "1037003810",
    "1037964797",
    "1038339037",
    "1039479857",
    "1040866065",
    "1041901725",
    "1040547601",
    "1041253305",
    "1041423372",
    "1042859116",
    "1043438784",
    "1044595372",
    "1045800392",
    "1047826818",
    "1048009338",
    "1048343892",
    "1048835785",
    "1048853697",
    "1049067283"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const FUTURENET_LIMITS: NetworkLimits = {
  "tx_max_instructions": 400000000,
  "tx_memory_limit": 41943040,
  "tx_max_footprint_entries": 400,
  "tx_max_disk_read_entries": 200,
  "tx_max_write_ledger_entries": 200,
  "tx_max_disk_read_bytes": 200000,
  "tx_max_write_bytes": 132096,
  "tx_max_contract_events_size_bytes": 16384,
  "contract_data_key_size_bytes": 250,
  "contract_max_size_bytes": 131072,
  "ledger_max_instructions": 580000000,
  "ledger_max_disk_read_entries": 1000,
  "ledger_max_disk_read_bytes": 400000,
  "ledger_max_write_ledger_entries": 1000,
  "ledger_max_write_bytes": 286720,
  "ledger_max_txs_size_bytes": 266240,
  "max_entry_ttl": 3110400,
  "min_temporary_ttl": 720,
  "min_persistent_ttl": 120960,
  "fee_rate_per_instructions_increment": 7,
  "fee_read_ledger_entry": "1563",
  "fee_write_ledger_entry": "2500",
  "fee_read_1kb": "447",
  "fee_write_1kb": "875",
  "fee_tx_size_1kb": "406",
  "fee_historical_1kb": "4059",
  "fee_contract_events_1kb": "5000",
  "persistent_rent_rate_denominator": "1215",
  "temp_rent_rate_denominator": "2430",
  "live_soroban_state_size_window": [
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549",
    "66868549"
  ],
  "state_target_size_bytes": "3000000000",
  "rent_fee_1kb_state_size_low": "-17000",
  "rent_fee_1kb_state_size_high": "10000",
  "state_size_rent_fee_growth_factor": 5000
} as const;

export const NETWORK_LIMITS: Record<string, NetworkLimits> = {
  mainnet: MAINNET_LIMITS,
  testnet: TESTNET_LIMITS,
  futurenet: FUTURENET_LIMITS,
} as const;
